server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.isvgzypggsiopsrrljew
    password: ${POSTGRES_PASSWORD}
    hikari:
      data-source-properties:
        prepareThreshold: 0
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false



    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: disabled
      password: disabled

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4.1-mini

jwt:
  secret: YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    #com.ablematch.able: OFF
    com.ablematch.able: INFO


naver:
  maps:
    base-url: https://maps.apigw.ntruss.com
    key-id: ${NAVER_MAPS_KEY_ID}
    key: ${NAVER_MAPS_KEY}
