server:
  port: 8090

saramin:
  api-key: "AAAAAAAAAAAA"

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.isvgzypggsiopsrrljew
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: disabled
      password: disabled

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4.1-mini

jwt:
  secret: YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh

